In [3]:
options(warn = -1)
options(repr.plot.width = 15, repr.plot.height = 9)
Sys.setlocale(category = "LC_ALL",locale = "ko_KR.UTF-8") # 한글 쓰려면 이 세개는 무조건 쓰고 들어가야 한다

[1] "ko_KR.UTF-8/ko_KR.UTF-8/ko_KR.UTF-8/C/ko_KR.UTF-8/C.UTF-8"

In [4]:
#  1 3 5 1 2 3 4 5 6 7 8 9 10 1 3 5 7 9 1 2 3 1 2 3
c(seq(1,5,2),1:10,seq(1,10,2),rep(1:3,2))

 [1]  1  3  5  1  2  3  4  5  6  7  8  9 10  1  3  5  7  9  1  2  3  1  2  3

In [6]:
c(1,3,5)
1:10
seq(1, 10, 2)
rep(1:3, 2)

[1] 1 3 5

 [1]  1  2  3  4  5  6  7  8  9 10

[1] 1 3 5 7 9

[1] 1 2 3 1 2 3

In [9]:
head(iris)
irisHead <- iris[1:6,]

  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa
2 4.9          3.0         1.4          0.2         setosa
3 4.7          3.2         1.3          0.2         setosa
4 4.6          3.1         1.5          0.2         setosa
5 5.0          3.6         1.4          0.2         setosa
6 5.4          3.9         1.7          0.4         setosa

In [11]:
# 행과 열을 뒤집기
t(irisHead) # matrix로 바뀐다

             1      2      3      4      5      6
Sepal.Length 5.1    4.9    4.7    4.6    5.0    5.4
Sepal.Width  3.5    3.0    3.2    3.1    3.6    3.9
Petal.Length 1.4    1.4    1.3    1.5    1.4    1.7
Petal.Width  0.2    0.2    0.2    0.2    0.2    0.4
Species      setosa setosa setosa setosa setosa setosa

In [12]:
seq(10, 150, 10)

 [1]  10  20  30  40  50  60  70  80  90 100 110 120 130 140 150

In [20]:
iris[1:100,]

    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1   5.1          3.5         1.4          0.2         setosa
2   4.9          3.0         1.4          0.2         setosa
3   4.7          3.2         1.3          0.2         setosa
4   4.6          3.1         1.5          0.2         setosa
5   5.0          3.6         1.4          0.2         setosa
6   5.4          3.9         1.7          0.4         setosa
7   4.6          3.4         1.4          0.3         setosa
8   5.0          3.4         1.5          0.2         setosa
9   4.4          2.9         1.4          0.2         setosa
10  4.9          3.1         1.5          0.1         setosa
11  5.4          3.7         1.5          0.2         setosa
12  4.8          3.4         1.6          0.2         setosa
13  4.8          3.0         1.4          0.1         setosa
14  4.3          3.0         1.1          0.1         setosa
15  5.8          4.0         1.2          0.2         setosa
16  5.7          4.4         1.5          0.4         setosa
17  5.4          3.9         1.3          0.4         setosa
18  5.1          3.5         1.4          0.3         setosa
19  5.7          3.8         1.7          0.3         setosa
20  5.1          3.8         1.5          0.3         setosa
21  5.4          3.4         1.7          0.2         setosa
22  5.1          3.7         1.5          0.4         setosa
23  4.6          3.6         1.0          0.2         setosa
24  5.1          3.3         1.7          0.5         setosa
25  4.8          3.4         1.9          0.2         setosa
26  5.0          3.0         1.6          0.2         setosa
27  5.0          3.4         1.6          0.4         setosa
28  5.2          3.5         1.5          0.2         setosa
29  5.2          3.4         1.4          0.2         setosa
30  4.7          3.2         1.6          0.2         setosa
⋮   ⋮            ⋮           ⋮            ⋮           ⋮
71  5.9          3.2         4.8          1.8         versicolor
72  6.1          2.8         4.0          1.3         versicolor
73  6.3          2.5         4.9          1.5         versicolor
74  6.1          2.8         4.7          1.2         versicolor
75  6.4          2.9         4.3          1.3         versicolor
76  6.6          3.0         4.4          1.4         versicolor
77  6.8          2.8         4.8          1.4         versicolor
78  6.7          3.0         5.0          1.7         versicolor
79  6.0          2.9         4.5          1.5         versicolor
80  5.7          2.6         3.5          1.0         versicolor
81  5.5          2.4         3.8          1.1         versicolor
82  5.5          2.4         3.7          1.0         versicolor
83  5.8          2.7         3.9          1.2         versicolor
84  6.0          2.7         5.1          1.6         versicolor
85  5.4          3.0         4.5          1.5         versicolor
86  6.0          3.4         4.5          1.6         versicolor
87  6.7          3.1         4.7          1.5         versicolor
88  6.3          2.3         4.4          1.3         versicolor
89  5.6          3.0         4.1          1.3         versicolor
90  5.5          2.5         4.0          1.3         versicolor
91  5.5          2.6         4.4          1.2         versicolor
92  6.1          3.0         4.6          1.4         versicolor
93  5.8          2.6         4.0          1.2         versicolor
94  5.0          2.3         3.3          1.0         versicolor
95  5.6          2.7         4.2          1.3         versicolor
96  5.7          3.0         4.2          1.2         versicolor
97  5.7          2.9         4.2          1.3         versicolor
98  6.2          2.9         4.3          1.3         versicolor
99  5.1          2.5         3.0          1.1         versicolor
100 5.7          2.8         4.1          1.3         versicolor

In [34]:
iris[seq(10, 150, 10),c(1,2)]

    Sepal.Length Sepal.Width
10  4.9          3.1
20  5.1          3.8
30  4.7          3.2
40  5.1          3.4
50  5.0          3.3
60  5.2          2.7
70  5.6          2.5
80  5.7          2.6
90  5.5          2.5
100 5.7          2.8
110 7.2          3.6
120 6.0          2.2
130 7.2          3.0
140 6.9          3.1
150 5.9          3.0

In [37]:
# row수
nrow(iris)

# Column수
ncol(iris)

length(iris)

[1] 150

[1] 5

[1] 5

In [39]:
# 기본 통계량
summary(iris)
# r에선 문자도 보여줌
summary(iris$Sepal.Length)

  Sepal.Length    Sepal.Width     Petal.Length    Petal.Width
 Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100
 1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300
 Median :5.800   Median :3.000   Median :4.350   Median :1.300
 Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199
 3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800
 Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500
       Species
 setosa    :50
 versicolor:50
 virginica :50

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  4.300   5.100   5.800   5.843   6.400   7.900

In [42]:
# factor Type인 Species에서 문자와 숫자로 각각 출력하기
as.character(iris$Species) # 문자만가지고 오기
as.numeric(iris$Species) # 숫자만 가지고 오기
# factor엔 같이 들어있어서

  [1] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
  [6] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
 [11] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
 [16] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
 [21] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
 [26] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
 [31] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
 [36] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
 [41] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
 [46] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"
 [51] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [56] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [61] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [66] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [71] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [76] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [81] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [86] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [91] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [96] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
[101] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"
[106] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"
[111] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"
[116] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"
[121] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"
[126] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"
[131] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"
[136] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"
[141] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"
[146] "virginica"  "virginica"  "virginica"  "virginica"  "virginica"

  [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 [38] 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 [75] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3
[112] 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
[149] 3 3

In [47]:
# 벡터 계산
x <- c(3,6,9,12,15)
x

x+1

y <- c(1,2,3)
length(x)
x + c(1,2,3,4,5)

[1]  3  6  9 12 15

[1]  4  7 10 13 16

[1] 5

[1]  4  8 12 16 20

In [51]:
y <- c(1,2,3,4,5)
if (length(x) == length(y)){
    print(x+y)
}else{
    print("done")
}

[1]  4  8 12 16 20

In [54]:
# 벡터 합치기
x <- c(10, 20, 30, 40, 50)
y <- c(1,2,3)
sort(append(x, y)) # 함수 만들때는 1개씩 더해줘야 하니까 append가 필요하다

sort(c(x, y)) # append안 하고 써줘도 된다

[1]  1  2  3 10 20 30 40 50

[1]  1  2  3 10 20 30 40 50

In [60]:
length(iris$Sepal.Length)

[1] 150

In [63]:
# Ex : iris의 Sepal.Length의 중복되지 않은 갯수의 percent 구하기
length(unique(iris$Sepal.Length)) / length(iris$Sepal.Length) * 100

[1] 23.33333

In [65]:
# Ex : iris의 Sepal.Length의 중복된 않은 갯수의 percent 구하기
(1-(length(unique(iris$Sepal.Length)) / length(iris$Sepal.Length))) * 100

[1] 76.66667

#### 문자열 관련 함수

In [66]:
# 여러개 벡터를 하나로 만들기
paste("Hello", "World!")

[1] "Hello World!"

In [67]:
paste(iris$Species[1], ":", iris$Species[51], ":", iris$Species[101])

[1] "setosa : versicolor : virginica"

In [73]:
print((iris$Species[1] &iris$Species[51]&iris$Species[101]))

[1] NA

In [78]:
paste("010", "1111", "2222")#기본값
paste("010", "1111", "2222", sep = " ")#기본값
paste("010", "1111", "2222", sep = "-")

[1] "010 1111 2222"

[1] "010 1111 2222"

[1] "010-1111-2222"

In [74]:
# 문자열 꾸미기
cat("Hello","\n","World!\n")
cat("aaa\tbbb\tccc")

Hello
 World!
aaa	bbb	ccc

In [80]:
# 문자열 추출하기
str01 <- "abcdefghijklmn"
substring(str01, 2, 5)

str02 <- "가나다라마바사"
substring(str02, 2, 5)

[1] "bcde"

[1] "나다라마"

In [84]:
x <- runif(5, 1, 20) # 파라메터 순서에 맞게 쓰면 max min 이렇게 안써도 된다 
x

[1] 18.956342 12.318628  7.201906  5.384763 11.294685

In [85]:
# x의 값들이 4와 7 사이에 있는지?
(x >= 4) & (x <= 7)

[1] FALSE FALSE FALSE  TRUE FALSE

In [86]:
# 데이터 갯수 _( 위를 통해 데이터 갯수를 알 수 있음)
sum((x >= 4) & (x <= 7))

[1] 1

In [88]:
# any, all _ 파이썬에도 있음
any(x >= 10)
all(x >= 10)

[1] TRUE

[1] FALSE

#### 행렬(Metrix)
: 데이터의 모든 Type이 일치되어야 구성

In [ ]:
vec1 <- c(1,2,3)
vec2 <- c(4,5,6)
vec3 <- c(7,8,9)
# 행렬은 다 더블임, 그래서 넘파이도 더블임

In [90]:
# rbind : row bind
mat1 <- rbind(vec1, vec2, vec3)
mat1

     [,1] [,2] [,3]
vec1 1    2    3
vec2 4    5    6
vec3 7    8    9

In [91]:
# CBIND : column bind
mat2 <- cbind(vec1, vec2, vec3)
mat2

     vec1 vec2 vec3
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

In [95]:
irisHead <- head(iris, 5)
irisHead
irisHead <- rbind(irisHead, c(1,1,1,1,'setosa'))

irisHead <- cbind(irisHead, abc=rep(2,6))

irisHead

  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa
2 4.9          3.0         1.4          0.2         setosa
3 4.7          3.2         1.3          0.2         setosa
4 4.6          3.1         1.5          0.2         setosa
5 5.0          3.6         1.4          0.2         setosa

  Sepal.Length Sepal.Width Petal.Length Petal.Width Species abc
1 5.1          3.5         1.4          0.2         setosa  2
2 4.9          3           1.4          0.2         setosa  2
3 4.7          3.2         1.3          0.2         setosa  2
4 4.6          3.1         1.5          0.2         setosa  2
5 5            3.6         1.4          0.2         setosa  2
6 1            1           1            1           setosa  2

In [101]:
irisHead <- iris[1:5,]
# Length = Sepal.Length + Petal.Length
irisHead <- cbind(irisHead, Length=(irisHead$Sepal.Length + irisHead$Petal.Length))
irisHead$Length2 <- irisHead$Sepal.Length + irisHead$Petal.Length

irisHead

  Sepal.Length Sepal.Width Petal.Length Petal.Width Species Length Length2
1 5.1          3.5         1.4          0.2         setosa  6.5    6.5
2 4.9          3.0         1.4          0.2         setosa  6.3    6.3
3 4.7          3.2         1.3          0.2         setosa  6.0    6.0
4 4.6          3.1         1.5          0.2         setosa  6.1    6.1
5 5.0          3.6         1.4          0.2         setosa  6.4    6.4

In [106]:
mat1
colnames(mat1) <- c("A", "B", "C") # 컬럼이름 주는 거 
mat1
class(mat1) # 타입을 알아보는 함수

mat1D <- as.data.frame(mat1)
mat1D

     A B C
vec1 1 2 3
vec2 4 5 6
vec3 7 8 9

     A B C
vec1 1 2 3
vec2 4 5 6
vec3 7 8 9

[1] "matrix" "array"

     A B C
vec1 1 2 3
vec2 4 5 6
vec3 7 8 9

In [109]:
mat2
# row 이름 추가
rownames(mat2) <- 1:3
mat2

# 이걸로 데이터 프레임 만들기
mat2D <- as.data.frame(mat2)
mat2D

  vec1 vec2 vec3
1 1    4    7
2 2    5    8
3 3    6    9

  vec1 vec2 vec3
1 1    4    7
2 2    5    8
3 3    6    9

  vec1 vec2 vec3
1 1    4    7
2 2    5    8
3 3    6    9

In [110]:
mat1D
mat2D

     A B C
vec1 1 2 3
vec2 4 5 6
vec3 7 8 9

  vec1 vec2 vec3
1 1    4    7
2 2    5    8
3 3    6    9

In [ ]:
colnames(mat2D) <- colnames(mat1D) # 컬럼이름을 바꿔주는 거 
rbind(mat1D, mat2D)

     A B C
vec1 1 2 3
vec2 4 5 6
vec3 7 8 9
1    1 4 7
2    2 5 8
3    3 6 9

In [113]:
colnames(mat2D)

[1] "A" "B" "C"

#### 데이터프레임
: 다양한 자료형으로 구성된 2차원 형태의 데이터 구조

In [114]:
# 벡터로 데이터 프레임 만들기
no <- 1:4
name <- c("Apple", "Banana", "Peach", "Berry")
price <- c(500, 400, 300, 200)
qty <- c(5, 2, 7, 9)

In [116]:
fruit <- data.frame(번호=no, 상품명=name, 금액=price, 재고량=qty)
fruit

  번호 상품명 금액 재고량
1 1    Apple  500  5
2 2    Banana 400  2
3 3    Peach  300  7
4 4    Berry  200  9

In [117]:
str(fruit)

'data.frame':	4 obs. of  4 variables:
 $ 번호  : int  1 2 3 4
 $ 상품명: chr  "Apple" "Banana" "Peach" "Berry"
 $ 금액  : num  500 400 300 200
 $ 재고량: num  5 2 7 9

In [124]:
# fruit에서 상품명과 재고량만 보기

fruit[, c("상품명", "재고량")]
fruit[, c(2, 4)]

  상품명 재고량
1 Apple  5
2 Banana 2
3 Peach  7
4 Berry  9

  상품명 재고량
1 Apple  5
2 Banana 2
3 Peach  7
4 Berry  9

In [ ]:
# fruit 에서 번호를 제외한 모든 내용보기
fruit

# 내가 한거 fruit[,c(-1)]
# 선생님
fruit[,-1]

  번호 상품명 금액 재고량
1 1    Apple  500  5
2 2    Banana 400  2
3 3    Peach  300  7
4 4    Berry  200  9

  상품명 금액 재고량
1 Apple  500  5
2 Banana 400  2
3 Peach  300  7
4 Berry  200  9

In [ ]:
# fruit에서 2,4번 행을 제외한 상품명, 금액, 재고량만 출력을 최소한의 코딩으로
fruit[-c(2,4),-1]
# 행, 열 순

  상품명 금액 재고량
1 Apple  500  5
3 Peach  300  7

In [136]:
# fruit에 재고금액(금액*재고량) 추가
fruit
fruit <- cbind(fruit, 재고금액=(fruit$`금액`*fruit$`재고량`))

  번호 상품명 금액 재고량 재고금액
1 1    Apple  500  5      2500
2 2    Banana 400  2       800
3 3    Peach  300  7      2100
4 4    Berry  200  9      1800

In [ ]:
# # fruit에 재고금액(금액*재고량) 추가_ 선생님이 하신거
# fruit$재고금액 = fruit$`금액`*fruit$`재고량`

In [ ]:
fruit$원산지 = c("한국","태국","한국","중국")

In [139]:
fruit

  번호 상품명 금액 재고량 재고금액 재고금액 원산지
1 1    Apple  500  5      2500     2500     한국
2 2    Banana 400  2       800      800     태국
3 3    Peach  300  7      2100     2100     한국
4 4    Berry  200  9      1800     1800     중국

### 외부 File 불러오기

In [ ]:
# txt file 불러오기
# read.table("../Data/emp.txt", header = T) # 헤더가 있는 애 라고 알려주는 거 
txtEmp <- read.table("../Data/emp.txt", header = T, sep = ",") # 컴마 기준으로 가져오는 거 
# 부등호를 쓰면 파이썬인지 아닌지 모름 그래서 화살표 쓰는거

In [148]:
str(txtEmp)

'data.frame':	3 obs. of  3 variables:
 $ 사번: int  101 201 301
 $ 이름: chr  "hong" "lee" "kim"
 $ 급여: int  150 250 300

In [150]:
csvEmp <- read.csv("../Data/emp2.csv", header = F) # 이건 헤더가 없는애라고 알려줌
colnames(csvEmp) <- c("사번", "이름", "급여")
csvEmp

  사번 이름   급여
1 101  홍길동 150
2 102  이순신 450
3 103  강감찬 500
4 104  유관순 350
5 105  김유신 400

In [151]:
# 컬럼이 몇개?
ncol(csvEmp)

[1] 3

In [152]:
# Row 갯수?
nrow(csvEmp)

[1] 5

In [159]:
c(1:5)
seq(2, 10, 2)
c('a':'e')

[1] 1 2 3 4 5

[1]  2  4  6  8 10

ERROR: Error in "a":"e": NA/NaN argument

In [160]:
# dataFrame 생성
df <- data.frame(
    x = 1:5,
    y = seq(2, 10, 2),
    z = c("a","b","c","d","e")
)

In [161]:
df

  x y  z
1 1  2 a
2 2  4 b
3 3  6 c
4 4  8 d
5 5 10 e

In [163]:
letters[1:5] # 벡터로 바꿔서 슬라이싱 해주면 가능,chracter은 없다

[1] "a" "b" "c" "d" "e"

In [166]:
# x와 y의 합계_ 벡터로 바꿔서 해줘야 한다 

df$x + df$y
sum(df$x)
sum(df$y)

[1]  3  6  9 12 15

[1] 15

[1] 30

#### 함수를 부르는 함수

In [ ]:
# 파이썬에선 .apply

In [ ]:
# 함수를 부르는 함수
apply(df[,1:2], 2,sum) # 2= 열방향 / 행은 1번
apply(df[,1:2], 2,mean) # 평균
apply(df[,1:2], 2,sd) # 표준편차

 x  y
15 30

In [169]:
df$Hap <- apply(df[,1:2], 1, sum)
df

  x y  z Hap
1 1  2 a  3
2 2  4 b  6
3 3  6 c  9
4 4  8 d 12
5 5 10 e 15

In [ ]:
# 부분집합
nrow(subset(df,x >=3 & y>=8)) # 데이터 프레임이라 로우로 확인_ sql에선 레코드 (row를 부르는거)

[1] 2

#### 두개 이상의 데이터 프레임 병합하기

In [180]:
height = data.frame(id=1:3,height=c(160,1170,180))
weight = data.frame(id=c(2,1,3),weight=c(70,60,80))
height
weight

  id height
1 1   160
2 2  1170
3 3   180

  id weight
1 2  70
2 1  60
3 3  80

In [181]:
merge(height, weight)

  id height weight
1 1   160   60
2 2  1170   70
3 3   180   80

In [185]:
height<-data.frame(id=1:3,height=c(160,170,180))
weight <- data.frame(ad=c(2,1),weight=c(70,60))
height
weight

  id height
1 1  160
2 2  170
3 3  180

  ad weight
1 2  70
2 1  60

In [186]:
merge(x=height, y = weight, by.x = "id",by.y = "ad")

  id height weight
1 1  160    60
2 2  170    70

In [187]:
merge(x=height, y = weight, by.x = "id",by.y = "ad", all.x = T)

  id height weight
1 1  160    60
2 2  170    70
3 3  180    NA

In [190]:
matrix(1:10)
matrix(1:10, nrow = 2)
matrix(1:10, nrow = 3, ncol = 2)

      [,1]
 [1,]  1
 [2,]  2
 [3,]  3
 [4,]  4
 [5,]  5
 [6,]  6
 [7,]  7
 [8,]  8
 [9,]  9
[10,] 10

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9
[2,] 2    4    6    8    10

     [,1] [,2]
[1,] 1    4
[2,] 2    5
[3,] 3    6

#### List
- 성격이 다른 자료구조로 생성이 가능
- key와 value로 구성

In [191]:
member <- list(name="홍길동", address="서울", tel="010-1111-2222", pay=300)
member

$name
[1] "홍길동"

$address
[1] "서울"

$tel
[1] "010-1111-2222"

$pay
[1] 300

In [192]:
member$address

[1] "서울"

#### 문자열 처리
수집한 데이터의 필요한 문자열을 자르고, 교체하고 수출하는 작업

## stringr package 사용 ( 파이썬엔 없음 )
- str_length() : 문자열 길이
- str_c() : 문자열 연결
- str_sub() : 범위에 해당하는 문자열 생성
- str_split() : 구분자를 기준으로 문자열을 분리하여 부분 생성
- str_replace() : 기존 문자열을 특정 문자열로 변환
- str_extract() : 문자열에서 특정 문자열 패턴의 첫번째 문자열 추가
- str_extract_all() : -> 모든 문자열 추출
- str_locate() : 문자열에서 특정 문자열 패턴의 첫번째 위치 추출
- str_locate_all() : -> 모든 문자열 추출

In [ ]:
# install.packages("stringr")  # pc에 한번 설치하고 불러올땐 라이브러리로

also installing the dependencies ‘magrittr’, ‘stringi’

The downloaded binary packages are in
	/var/folders/7v/t26g0nsx69l66fs_rjzzq1s00000gn/T//RtmpUyBjEC/downloaded_packages

In [ ]:
library(stringr) # 문자열 처리 할 게 있으면 무조건 이거씀_ 편해서

Attaching package: ‘stringr’


The following object is masked _by_ ‘.GlobalEnv’:

    fruit

In [204]:
string <- "hongkildong105youbi1002kwanwoo25장비2005"

In [205]:
# a ~ z 까지의 영문자가 연속으로 3개 발견된 문자열 추출
str_extract_all(string, "[a-z]{3}") # 뒤에 패턴을 준것

[[1]]
[1] "hon" "gki" "ldo" "you" "kwa" "nwo"

In [206]:
# a ~ z 까지의 영문자가 연속으로 3개~5개 발견된 문자열 추출
str_extract_all(string, "[a-z]{3,5}") # 뒤에 패턴을 준것

[[1]]
[1] "hongk" "ildon" "youbi" "kwanw"

In [207]:
# a~z까지의 영문자가 연속으로 1개 이상 발견된 문자열 추출
str_extract_all(string, "[a-z]{1,}")

[[1]]
[1] "hongkildong" "youbi"       "kwanwoo"

In [208]:
# a~z까지의 영문자가 연속으로 1개이상 발견된 문자열 추출 
aaa <- str_extract_all(string,"[a-z]{1,}")
class(aaa)
bbb <- unlist(aaa)
bbb

[1] "list"

[1] "hongkildong" "youbi"       "kwanwoo"

In [218]:
# 숫자만 추출하기
str_extract_all(string,("[a-z]{1,}"))

[[1]]
[1] "hongkildong" "youbi"       "kwanwoo"

In [220]:
str_extract_all(string, "[0-9]{1,}")

[[1]]
[1] "105"  "1002" "25"   "2005"

In [223]:
as.numeric(unlist(str_extract_all(string, "[0-9]{1,}")))

[1]  105 1002   25 2005

In [228]:
# 한글만 추출하기
str_extract_all(string,("[ㄱ-ㅎ]{1,}"))

[[1]]
character(0)

In [229]:
str_extract_all(string, "[가-히]{1,}")

[[1]]
[1] "장비"

In [231]:
str_extract_all(string, "[각-힣]{1,}")

[[1]]
[1] "장비"

In [230]:
str_extract_all(string, "[가-힣]{1,}")

[[1]]
[1] "장비"

In [ ]:
# 영문자를 제외한 문자 출력하기 _ 정규식에쓰임
str_extract_all(string,"[^a-z]{1,}")

[[1]]
[1] "105"        "1002"       "25장비2005"

In [ ]:
# 문자열 길이 구하기
str_locate(string,"장비") # 장비의 앞에 있는 거 가져옴

     start end
[1,] 33    34

In [239]:
str_sub(string,1,32)
str_sub(string,1,str_locate(string,"장비")[1]-1) # 장비 위치가 바뀌어도 잘 가지고 오니까 이렇게 씀

[1] "hongkildong105youbi1002kwanwoo25"

[1] "hongkildong105youbi1002kwanwoo25"

In [240]:
# 대문자 소문자 변경하기
str_to_upper(string)
str_to_lower(string)

[1] "HONGKILDONG105YOUBI1002KWANWOO25장비2005"

[1] "hongkildong105youbi1002kwanwoo25장비2005"

In [245]:
# 문자열 교체하기
string <- str_replace(string, "hongkildong105", "홍길동35,")
string <- str_replace(string, "yoube1002", "유비45,")
string <- str_replace(string, "kwanwoo25", "관우25,")
string <- str_replace(string, "2005", "20")
string

[1] "홍길동35,youbi1002관우25,장비20,"

In [246]:
# 문자열 분리하기
str_split(string,",")

[[1]]
[1] "홍길동35"        "youbi1002관우25" "장비20"          ""

In [247]:
# 문자열 분리하기
unlist(str_split(string,","))

[1] "홍길동35"        "youbi1002관우25" "장비20"          ""

In [249]:
# 천단위 숫자가 들어간 문자열을 숫자로 변경하기
price <- "123,456,789"
as.numeric(str_replace_all(price,",",""))
as.numeric(str_remove_all(price,","))

[1] 123456789

[1] 123456789

In [255]:
# Na를 변경하기
temp <- c(1, 2, NA, 4)
temp
str_replace_all(str_replace_na(temp), 'NA', "3")

[1]  1  2 NA  4

[1] "1" "2" "3" "4"

In [253]:
# Na를 제거하기
temp <- c(1, 2, NA, 4)
temp
na.omit(temp)

[1]  1  2 NA  4

[1] 1 2 4
attr(,"na.action")
[1] 3
attr(,"class")
[1] "omit"