#### for문

In [2]:
# 1~ 10 까지의 숫자 출력
for(i in 1:10){
    print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10

In [3]:
for(i in c(1,3,5)){
    cat(i,"\n")
}

1
3
5

In [6]:
# 1~10까지의 홀수
for(i in 1:10){
    if(i%%2 ==1){
        print(i)
    }
}

[1] 1
[1] 3
[1] 5
[1] 7
[1] 9

In [7]:
# 1~10까지의 홀수 _ 선생님 정당
for(i in seq(1,10,2)){
    print(i)
}

[1] 1
[1] 3
[1] 5
[1] 7
[1] 9

In [12]:
for(i in seq(1,10)){
    print(i ,"=>" ,sqrt(i))
}

Warning message in print.default(i, "=>", sqrt(i)):
“NAs introduced by coercion”

ERROR: Error in print.default(i, "=>", sqrt(i)): invalid printing digits -2147483648

In [15]:
for(i in seq(1,10)){
    cat(i ,"=>" ,sqrt(i),"\n")
}

1 => 1
2 => 1.414214
3 => 1.732051
4 => 2
5 => 2.236068
6 => 2.44949
7 => 2.645751
8 => 2.828427
9 => 3
10 => 3.162278

In [11]:
# 예제 선생님 정답
for(i in 1:10){
    cat(i ,"=>" ,sqrt(i),"\n")
}

1 => 1
2 => 1.414214
3 => 1.732051
4 => 2
5 => 2.236068
6 => 2.44949
7 => 2.645751
8 => 2.828427
9 => 3
10 => 3.162278

In [17]:
# 예제 선생님 정답_최종
for(i in 1:10){
    cat(paste(i ,"=>" ,sqrt(i),"\n"))
}

1 => 1
2 => 1.4142135623731
3 => 1.73205080756888
4 => 2
5 => 2.23606797749979
6 => 2.44948974278318
7 => 2.64575131106459
8 => 2.82842712474619
9 => 3
10 => 3.16227766016838

In [18]:
# excel에서 q3 컬럼 데이터의 홀수의 합과 짝수의 합 구하기
# 출력 : 홀수의 합은 ___ 이고 짝수의 합은 ____ 입니다.

# csv file 
excel <- read.csv("../Data/excel.csv")
head(excel)

  q1 q2 q3 q4 q5
1 2  4  4  2  2
2 1  2  2  2  2
3 2  3  4  3  3
4 3  5  5  3  3
5 3  2  4  4  4
6 4  3  3  4  2

In [19]:
excel$q3

  [1] 4 2 4 5 4 3 4 4 5 4 4 4 4 3 2 2 1 3 4 4 5 4 2 4 4 3 4 5 2 4 5 4 4 5 5 3 5
 [38] 4 4 4 4 4 2 1 4 5 4 2 4 4 3 4 3 2 3 2 2 4 5 4 4 3 2 4 4 3 3 3 5 4 4 2 4 5
 [75] 4 4 4 4 2 5 2 4 4 2 4 4 5 4 2 4 3 3 5 5 2 4 5 3 1 4 4 3 2 2 3 5 2 5 3 3 4
[112] 4 4 3 4 5 4 2 4 5 3 2 3 2 4 4 2 4 5 2 4 2 3 3 4 4 4 5 5 4 3 5 5 5 4 3 2 5
[149] 3 4 2 4 2 4 4 5 2 4 5 3 4 5 4 4 2 4 5 2 4 2 3 3 4 4 4 5 5 4 3 5 5 5 4 3 2
[186] 5 3 4 2 4 2 4 4 2 5 3 3 4 4 4 3 4 5 4 2 4 5 3 2 3 2 4 4 2 4 3 3 4 4 4 5 5
[223] 4 3 5 5 5 4 3 2 5 3 4 2 4 2 4 4 5 2 4 5 3 4 5 4 4 4 2 4 4 2 5 3 3 4 4 4 3
[260] 4 5 4 2 4 5 3 2 3 4 3 2 5 3 4 2 4 2 4 4 5 2 4 5 3 4 5 4 4 4 2 4 4 2 5 3 3
[297] 4 4 4 3 4 5 4 2 4 5 3 4 3 2 5 3 4 2 4 2 4 4 5 2 4 5 3 4 5 4 4 4 2 4 4 2 5
[334] 3 3 4 4 4 3 4 5 4 2 4 5 3 4 2 4 2 4 4 5 2 4 5 3 4 5 4 4 4 2 4 4 2 5 3 3 4
[371] 4 4 3 4 5 4 2 4 5 3 2 3 4 3 2 5 3 4 2 4 2 4 4 5 2 4 5 3 4 5 4 4

In [ ]:
ifelse(excel$q3%%2 == 0, paste(a,":짝수"),paste(a,":홀수"))

In [ ]:
# 내가 한거  
q3 <- excel$q3
ifelse(q3%%2 == 0, even <-q3, 0)
ifelse(q3%%2 == 0, 0, odd <-q3)
cat("홀수의 합은",sum(even),"짝수의 합은",sum(odd))

  [1] 4 2 4 0 4 0 4 4 0 4 4 4 4 0 2 2 0 0 4 4 0 4 2 4 4 0 4 0 2 4 0 4 4 0 0 0 0
 [38] 4 4 4 4 4 2 0 4 0 4 2 4 4 0 4 0 2 0 2 2 4 0 4 4 0 2 4 4 0 0 0 0 4 4 2 4 0
 [75] 4 4 4 4 2 0 2 4 4 2 4 4 0 4 2 4 0 0 0 0 2 4 0 0 0 4 4 0 2 2 0 0 2 0 0 0 4
[112] 4 4 0 4 0 4 2 4 0 0 2 0 2 4 4 2 4 0 2 4 2 0 0 4 4 4 0 0 4 0 0 0 0 4 0 2 0
[149] 0 4 2 4 2 4 4 0 2 4 0 0 4 0 4 4 2 4 0 2 4 2 0 0 4 4 4 0 0 4 0 0 0 0 4 0 2
[186] 0 0 4 2 4 2 4 4 2 0 0 0 4 4 4 0 4 0 4 2 4 0 0 2 0 2 4 4 2 4 0 0 4 4 4 0 0
[223] 4 0 0 0 0 4 0 2 0 0 4 2 4 2 4 4 0 2 4 0 0 4 0 4 4 4 2 4 4 2 0 0 0 4 4 4 0
[260] 4 0 4 2 4 0 0 2 0 4 0 2 0 0 4 2 4 2 4 4 0 2 4 0 0 4 0 4 4 4 2 4 4 2 0 0 0
[297] 4 4 4 0 4 0 4 2 4 0 0 4 0 2 0 0 4 2 4 2 4 4 0 2 4 0 0 4 0 4 4 4 2 4 4 2 0
[334] 0 0 4 4 4 0 4 0 4 2 4 0 0 4 2 4 2 4 4 0 2 4 0 0 4 0 4 4 4 2 4 4 2 0 0 0 4
[371] 4 4 0 4 0 4 2 4 0 0 2 0 4 0 2 0 0 4 2 4 2 4 4 0 2 4 0 0 4 0 4 4

  [1] 0 0 0 5 0 3 0 0 5 0 0 0 0 3 0 0 1 3 0 0 5 0 0 0 0 3 0 5 0 0 5 0 0 5 5 3 5
 [38] 0 0 0 0 0 0 1 0 5 0 0 0 0 3 0 3 0 3 0 0 0 5 0 0 3 0 0 0 3 3 3 5 0 0 0 0 5
 [75] 0 0 0 0 0 5 0 0 0 0 0 0 5 0 0 0 3 3 5 5 0 0 5 3 1 0 0 3 0 0 3 5 0 5 3 3 0
[112] 0 0 3 0 5 0 0 0 5 3 0 3 0 0 0 0 0 5 0 0 0 3 3 0 0 0 5 5 0 3 5 5 5 0 3 0 5
[149] 3 0 0 0 0 0 0 5 0 0 5 3 0 5 0 0 0 0 5 0 0 0 3 3 0 0 0 5 5 0 3 5 5 5 0 3 0
[186] 5 3 0 0 0 0 0 0 0 5 3 3 0 0 0 3 0 5 0 0 0 5 3 0 3 0 0 0 0 0 3 3 0 0 0 5 5
[223] 0 3 5 5 5 0 3 0 5 3 0 0 0 0 0 0 5 0 0 5 3 0 5 0 0 0 0 0 0 0 5 3 3 0 0 0 3
[260] 0 5 0 0 0 5 3 0 3 0 3 0 5 3 0 0 0 0 0 0 5 0 0 5 3 0 5 0 0 0 0 0 0 0 5 3 3
[297] 0 0 0 3 0 5 0 0 0 5 3 0 3 0 5 3 0 0 0 0 0 0 5 0 0 5 3 0 5 0 0 0 0 0 0 0 5
[334] 3 3 0 0 0 3 0 5 0 0 0 5 3 0 0 0 0 0 0 5 0 0 5 3 0 5 0 0 0 0 0 0 0 5 3 3 0
[371] 0 0 3 0 5 0 0 0 5 3 0 3 0 3 0 5 3 0 0 0 0 0 0 5 0 0 5 3 0 5 0 0

홀수의 합은 1456 짝수의 합은 1456

In [22]:
sum(even)

[1] 1456

In [23]:
sum(odd)

[1] 1456

In [35]:
# excel에서 q3 컬럼 데이터의 홀수의 합과 짝수의 합 구하기 
# 출력 홀수의 합은 _ 이고 짝수의 합은 _입니다
excel <- read.csv("../Data/excel.csv")
head(excel)
num1 <- 0
num2 <- 0
for (i in excel$q3){
    if(i%%2 == 0){
        num1 <- num1 + i
    }else{
    num2 <- num2 + i
    }
}
cat("홀수의 합은",num2,"이고","짝수의 합은",num1,"입니다")

  q1 q2 q3 q4 q5
1 2  4  4  2  2
2 1  2  2  2  2
3 2  3  4  3  3
4 3  5  5  3  3
5 3  2  4  4  4
6 4  3  3  4  2

홀수의 합은 604 이고 짝수의 합은 852 입니다

In [37]:
# 선생님 정답 2
cat("홀수의 합은",sum(ifelse(q3%%2 == 1, q3, 0)), "이고 " )
cat("짝수의 합은",sum(ifelse(q3%%2 == 0, q3,0 )), "입니다." )

홀수의 합은 604 이고 짝수의 합은 852 입니다.

In [39]:
# 구구단 2단 출력

dan <- 2
for(i in 1:9){
    cat(dan, "X", i, "=",dan*i, "\n")
}

2 X 1 = 2
2 X 2 = 4
2 X 3 = 6
2 X 4 = 8
2 X 5 = 10
2 X 6 = 12
2 X 7 = 14
2 X 8 = 16
2 X 9 = 18

#### 함수

In [40]:
gugu <- function(dan){
    for(i in 1:9){
        cat(dan, "X", i, "=",dan*i, "\n")
    }
}

In [42]:
gugu(5)

5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45

In [44]:
seq(1,10)

 [1]  1  2  3  4  5  6  7  8  9 10

In [45]:
# gugu()를 이용한 구구단 전체 출력
gugu(seq(2,9))

2 3 4 5 6 7 8 9 X 1 = 2 3 4 5 6 7 8 9
2 3 4 5 6 7 8 9 X 2 = 4 6 8 10 12 14 16 18
2 3 4 5 6 7 8 9 X 3 = 6 9 12 15 18 21 24 27
2 3 4 5 6 7 8 9 X 4 = 8 12 16 20 24 28 32 36
2 3 4 5 6 7 8 9 X 5 = 10 15 20 25 30 35 40 45
2 3 4 5 6 7 8 9 X 6 = 12 18 24 30 36 42 48 54
2 3 4 5 6 7 8 9 X 7 = 14 21 28 35 42 49 56 63
2 3 4 5 6 7 8 9 X 8 = 16 24 32 40 48 56 64 72
2 3 4 5 6 7 8 9 X 9 = 18 27 36 45 54 63 72 81

In [62]:
for (i in seq(2,9)){
    cat(i,"단","======","\n")
    cat("\n",gugu(i))
}

2 단 ======
2 X 1 = 2
2 X 2 = 4
2 X 3 = 6
2 X 4 = 8
2 X 5 = 10
2 X 6 = 12
2 X 7 = 14
2 X 8 = 16
2 X 9 = 18

3 단 ======
3 X 1 = 3
3 X 2 = 6
3 X 3 = 9
3 X 4 = 12
3 X 5 = 15
3 X 6 = 18
3 X 7 = 21
3 X 8 = 24
3 X 9 = 27

4 단 ======
4 X 1 = 4
4 X 2 = 8
4 X 3 = 12
4 X 4 = 16
4 X 5 = 20
4 X 6 = 24
4 X 7 = 28
4 X 8 = 32
4 X 9 = 36

5 단 ======
5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45

6 단 ======
6 X 1 = 6
6 X 2 = 12
6 X 3 = 18
6 X 4 = 24
6 X 5 = 30
6 X 6 = 36
6 X 7 = 42
6 X 8 = 48
6 X 9 = 54

7 단 ======
7 X 1 = 7
7 X 2 = 14
7 X 3 = 21
7 X 4 = 28
7 X 5 = 35
7 X 6 = 42
7 X 7 = 49
7 X 8 = 56
7 X 9 = 63

8 단 ======
8 X 1 = 8
8 X 2 = 16
8 X 3 = 24
8 X 4 = 32
8 X 5 = 40
8 X 6 = 48
8 X 7 = 56
8 X 8 = 64
8 X 9 = 72

9 단 ======
9 X 1 = 9
9 X 2 = 18
9 X 3 = 27
9 X 4 = 36
9 X 5 = 45
9 X 6 = 54
9 X 7 = 63
9 X 8 = 72
9 X 9 = 81

In [63]:
# gugu()를 이용한 구구단 전체 출력 _ 선생님 정답

In [64]:
for(dan in 2:9){
    cat(">>>", dan, "단", "<<<\n")
    gugu(dan)
    cat("-----------------\n")
}

>>> 2 단 <<<
2 X 1 = 2
2 X 2 = 4
2 X 3 = 6
2 X 4 = 8
2 X 5 = 10
2 X 6 = 12
2 X 7 = 14
2 X 8 = 16
2 X 9 = 18
-----------------
>>> 3 단 <<<
3 X 1 = 3
3 X 2 = 6
3 X 3 = 9
3 X 4 = 12
3 X 5 = 15
3 X 6 = 18
3 X 7 = 21
3 X 8 = 24
3 X 9 = 27
-----------------
>>> 4 단 <<<
4 X 1 = 4
4 X 2 = 8
4 X 3 = 12
4 X 4 = 16
4 X 5 = 20
4 X 6 = 24
4 X 7 = 28
4 X 8 = 32
4 X 9 = 36
-----------------
>>> 5 단 <<<
5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45
-----------------
>>> 6 단 <<<
6 X 1 = 6
6 X 2 = 12
6 X 3 = 18
6 X 4 = 24
6 X 5 = 30
6 X 6 = 36
6 X 7 = 42
6 X 8 = 48
6 X 9 = 54
-----------------
>>> 7 단 <<<
7 X 1 = 7
7 X 2 = 14
7 X 3 = 21
7 X 4 = 28
7 X 5 = 35
7 X 6 = 42
7 X 7 = 49
7 X 8 = 56
7 X 9 = 63
-----------------
>>> 8 단 <<<
8 X 1 = 8
8 X 2 = 16
8 X 3 = 24
8 X 4 = 32
8 X 5 = 40
8 X 6 = 48
8 X 7 = 56
8 X 8 = 64
8 X 9 = 72
-----------------
>>> 9 단 <<<
9 X 1 = 9
9 X 2 = 18
9 X 3 = 27
9 X 4 = 36
9 X 5 = 45
9 X 6 = 54
9 X 7 = 63
9 X 8 = 72
9 X 9 = 81
-----------------

In [65]:
gugu <- function(dan, num){
    for(i in 1:num){
        cat(dan, "X", i, "=",dan*i, "\n")
    }
}

In [66]:
gugu(2, 12)

2 X 1 = 2
2 X 2 = 4
2 X 3 = 6
2 X 4 = 8
2 X 5 = 10
2 X 6 = 12
2 X 7 = 14
2 X 8 = 16
2 X 9 = 18
2 X 10 = 20
2 X 11 = 22
2 X 12 = 24

In [67]:
# 2개의 벡터 자료를 함께 출력하기
score <- c(85, 95, 89)
name <- c("유비", "관우", "장비")

In [73]:
for (num in score){
    for(n in name){
        print(n, num)
    }
}

ERROR: Error in print.default(n, num): invalid printing digits 85

In [ ]:
for(i in 1:length(score)){
    cat(name[i], score[i], "\n")
}

유비 85
관우 95
장비 89

In [ ]:
# 선생님 정답_ paste를 활용해야 함

cat(paste(name, ";", score, "\n"), sep="")

유비 ; 85
관우 ; 95
장비 ; 89

#### while

In [76]:
i <- 0 
while(i<10){
    i<-i+1
    print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10

#### repeat

In [ ]:
i <- 0
repeat{
    i <- i+1
    if(i>10){
        break
    }
    print(i)
}

# repeat 는 소괄호가 없음

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10