#### 기초 통계량 산출

In [1]:
cafe <- read.csv("../Data/coffee.csv")
head(cafe)

  seq Day.Code Day.of.Week Coffee Fruit.Cup
1 1   1        Mon          3     1
2 2   2        Tue          8     0
3 3   3        Wed         11     0
4 4   4        Thu         24     0
5 5   5        Fri          5     5
6 6   6        Sat         10     0

In [2]:
# 빈도수
table(cafe$Coffee)

 3  5  8  9 10 11 13 14 18 22 24 25 27 29 33 34 49 50 51 53 54 56 59
 1  2  1  1  1  2  1  1  1  1  1  1  1  2  1  2  1  2  1  1  1  1  1

In [4]:
# 범위 빈도수
coffee_range = seq(0, 60, 10)
table(cut(cafe$Coffee, breaks = coffee_range, right = F))

 [0,10) [10,20) [20,30) [30,40) [40,50) [50,60)
      5       6       6       3       1       7

In [ ]:
# 줄기-잎 그림
stem(cafe$Coffee) # 갯수 파악

  The decimal point is 1 digit(s) to the right of the |

  0 | 35589
  1 | 011348
  2 | 245799
  3 | 344
  4 | 9
  5 | 0013469

In [ ]:
# Coffee와 쥬스의 변동계수 구하기 
(cafe$Coffee)

 [1]  3  8 11 24  5 10 22 25 27 13  5  9 11 14 18 29 33 34 29 50 51 54 53 56 59
[26] 34 49 50

In [7]:
# 평균, 표준편차, 변동계수 계산
coffee.mean <- mean(cafe$Coffee)
coffee.sd <- sd(cafe$Coffee)
coffee.cv <- coffee.sd / coffee.mean

juice.mean <- mean(cafe$Fruit.Cup)
juice.sd <- sd(cafe$Fruit.Cup)
juice.cv <- juice.sd / juice.mean

data.frame(
  음료 = c("Coffee", "Juice"),
  평균 = c(coffee.mean, juice.mean),
  표준편차 = c(coffee.sd, juice.sd),
  변동계수 = c(coffee.cv, juice.cv)
)

  음료   평균      표준편차  변동계수
1 Coffee 28.071429 18.269441 0.6508198
2 Juice   6.071429  6.548557 1.0785858

In [ ]:
# Coffee와 쥬스의 변동계수 구하기