In [3]:
# Data 불러오기

import pandas as pd
csv = pd.read_csv("../Data/bmi.csv")
csv.head()

   height  weight   label
0     187      35    thin
1     144      68     fat
2     172      66  normal
3     156      54  normal
4     128      54     fat

In [16]:
# Data 갯수 확인하기 
csv.shape # 내가 한거
csv.count() # 선생님이 하신 거

height    20000
weight    20000
label     20000
dtype: int64

In [ ]:
# 기본 통계량
csv.describe()

# 값차이가 나니 , 정규화 해야 겠다 하고 봐야 함

             height        weight
count  20000.000000  20000.000000
mean     159.626350     57.419150
std       23.292565     13.193164
min      120.000000     35.000000
25%      139.000000     46.000000
50%      160.000000     57.000000
75%      180.000000     69.000000
max      200.000000     80.000000

In [17]:
# label 종류 확인 
csv.label.unique() # 내가 한거
csv['label'].unique() # 선생님이 하신거

<StringArray>
['thin', 'fat', 'normal']
Length: 3, dtype: str

In [ ]:
# Data Type 확인하기
csv.info() # 내가 한거_ 이건 결측치 확인
csv.dtypes # 선생님이 하신 거

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   height  20000 non-null  int64
 1   weight  20000 non-null  int64
 2   label   20000 non-null  str
dtypes: int64(2), str(1)
memory usage: 468.9 KB

height    int64
weight    int64
label       str
dtype: object

#### Data 정규화

In [19]:
# weight, height
csv['weight'] = csv['weight'] / csv['weight'].max()
csv['height'] = csv['height'] / csv['height'].max()

csv.head()

   height  weight   label
0   0.935  0.4375    thin
1   0.720  0.8500     fat
2   0.860  0.8250  normal
3   0.780  0.6750  normal
4   0.640  0.6750     fat

In [32]:
# label
bclass = {
    'thin' : [1,0,0],
    'normal' : [0,1,0],
    'fat' : [0,0,1]
}

y = []
for v in csv['label']:
    # print(v)
    y.append(bclass[v])

---
#### 훈련용과 테스트

In [33]:
# Train
X_train = csv[['height', 'weight']][:15000]
y_train = y[:15000]

In [34]:
X_train.tail()

       height  weight
14995   0.825  0.5000
14996   0.790  0.8875
14997   0.700  0.7375
14998   0.975  0.7000
14999   0.780  0.5000

In [35]:
len(X_train)

15000

In [36]:
y_train[:5]

[[1, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 0, 1]]

In [37]:
len(y_train)

15000

In [38]:
# Test Data
X_test = csv[['height', 'weight']][15001:]
y_test = y[15001:]

In [39]:
X_test.tail()

       height  weight
19995   0.800  0.8375
19996   0.685  0.4375
19997   0.875  0.8375
19998   0.970  0.8500
19999   0.990  0.7875

In [40]:
y_test[:5]

[[0, 1, 0], [1, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 0]]

---
#### Deep Learning Model 만들기

In [41]:
# 입력층 : 2개
# 은닉층 : 512, activation = 'relu'
# 출력층 : 3개 ,activation = 'softmax' : 다중 분류 문제이기 때문에 softmax 사용
# loss : optimizer  = 'rmsprop', loss = 'categorical_crossentropy' : 다중 분류 문제이기 때문에 categorical_crossentropy 사용

In [42]:
from tensorflow import keras
from tensorflow.keras.layers import Input
# 입력층 : 3 
# 은닉층 : 32
# 출력층 : 1
# activation : signoid, tanh ,relu,leakyRelu


model = keras.Sequential()
model.add(Input(shape=(2,)))
model.add(keras.layers.Dense(512,activation='relu')) # 은닉층 : 2의 배수
model.add(keras.layers.Dense(3,activation='softmax'))

In [43]:
model.compile(
    optimizer= 'rmsprop',
    loss ='categorical_crossentropy',
    metrics =['accuracy']
)

In [ ]:
# 학습 시키기 
import numpy as np
model.fit(
    np.array(X_train),
    np.array(y_train),
    epochs = 100, # 처음에 5로 해본 뒤 , 50번씩 해보기
    
)

Epoch 1/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 469us/step - accuracy: 0.7537 - loss: 0.6743
Epoch 2/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 459us/step - accuracy: 0.9354 - loss: 0.3079
Epoch 3/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 423us/step - accuracy: 0.9639 - loss: 0.2003
Epoch 4/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 442us/step - accuracy: 0.9687 - loss: 0.1567
Epoch 5/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 415us/step - accuracy: 0.9711 - loss: 0.1314
Epoch 6/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 465us/step - accuracy: 0.9735 - loss: 0.1153
Epoch 7/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.9741 - loss: 0.1049
Epoch 8/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.9731 - loss: 0.0971
Epoch 9/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.9743 - loss: 0.0904
Epoch 10/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.9749 - loss: 0.0853
Epoch 11/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 688us/step - accuracy: 0.9762 - loss: 0.0822
Epoch 12/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 462us/step - accuracy: 0.9767 - loss: 0.0779
Epoch 13/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 451us/step - accuracy: 0.9777 - loss: 0.0756
Epoch 14/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 442us/step - accuracy: 0.9766 - loss: 0.0731
Epoch 15/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - accuracy: 0.9772 - loss: 0.0710
Epoch 16/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 422us/step - accuracy: 0.9761 - loss: 0.0698
Epoch 17/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 440us/step - accuracy: 0.9787 - loss: 0.0681
Epoch 18/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 488us/step - accuracy: 0.9772 - loss: 0.0669
Epoch 19/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 417us/step - accuracy: 0.9781 - loss: 0.0646
Epoch 20/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.9772 - loss: 0.0640
Epoch 21/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 469us/step - accuracy: 0.9780 - loss: 0.0627
Epoch 22/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 496us/step - accuracy: 0.9765 - loss: 0.0626
Epoch 23/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.9772 - loss: 0.0609
Epoch 24/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 439us/step - accuracy: 0.9781 - loss: 0.0608
Epoch 25/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 440us/step - accuracy: 0.9769 - loss: 0.0603
Epoch 26/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 449us/step - accuracy: 0.9781 - loss: 0.0599
Epoch 27/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step - accuracy: 0.9781 - loss: 0.0591
Epoch 28/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 417us/step - accuracy: 0.9771 - loss: 0.0574
Epoch 29/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 499us/step - accuracy: 0.9772 - loss: 0.0575
Epoch 30/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 512us/step - accuracy: 0.9777 - loss: 0.0581
Epoch 31/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 455us/step - accuracy: 0.9771 - loss: 0.0567
Epoch 32/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 447us/step - accuracy: 0.9767 - loss: 0.0569
Epoch 33/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 443us/step - accuracy: 0.9775 - loss: 0.0562
Epoch 34/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 453us/step - accuracy: 0.9771 - loss: 0.0558
Epoch 35/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 467us/step - accuracy: 0.9789 - loss: 0.0544
Epoch 36/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 423us/step - accuracy: 0.9780 - loss: 0.0551
Epoch 37/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.9780 - loss: 0.0541
Epoch 38/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.9780 - loss: 0.0536
Epoch 39/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 447us/step - accuracy: 0.9784 - loss: 0.0538
Epoch 40/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 497us/step - accuracy: 0.9789 - loss: 0.0528
Epoch 41/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 646us/step - accuracy: 0.9785 - loss: 0.0532
Epoch 42/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.9785 - loss: 0.0529
Epoch 43/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 442us/step - accuracy: 0.9794 - loss: 0.0524
Epoch 44/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 489us/step - accuracy: 0.9771 - loss: 0.0523
Epoch 45/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 481us/step - accuracy: 0.9791 - loss: 0.0514
Epoch 46/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 503us/step - accuracy: 0.9775 - loss: 0.0525
Epoch 47/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 482us/step - accuracy: 0.9781 - loss: 0.0520
Epoch 48/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 520us/step - accuracy: 0.9774 - loss: 0.0517
Epoch 49/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 474us/step - accuracy: 0.9781 - loss: 0.0501
Epoch 50/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 599us/step - accuracy: 0.9783 - loss: 0.0510
Epoch 51/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.9790 - loss: 0.0505
Epoch 52/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.9783 - loss: 0.0517
Epoch 53/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.9785 - loss: 0.0507
Epoch 54/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 461us/step - accuracy: 0.9792 - loss: 0.0503
Epoch 55/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 565us/step - accuracy: 0.9785 - loss: 0.0500
Epoch 56/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 438us/step - accuracy: 0.9787 - loss: 0.0496
Epoch 57/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 464us/step - accuracy: 0.9784 - loss: 0.0494
Epoch 58/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 453us/step - accuracy: 0.9787 - loss: 0.0490
Epoch 59/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 437us/step - accuracy: 0.9785 - loss: 0.0500
Epoch 60/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 467us/step - accuracy: 0.9791 - loss: 0.0484
Epoch 61/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 476us/step - accuracy: 0.9789 - loss: 0.0487
Epoch 62/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 686us/step - accuracy: 0.9794 - loss: 0.0496
Epoch 63/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.9794 - loss: 0.0486
Epoch 64/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 508us/step - accuracy: 0.9781 - loss: 0.0493
Epoch 65/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 518us/step - accuracy: 0.9781 - loss: 0.0482
Epoch 66/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 479us/step - accuracy: 0.9786 - loss: 0.0486
Epoch 67/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 483us/step - accuracy: 0.9789 - loss: 0.0479
Epoch 68/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 413us/step - accuracy: 0.9789 - loss: 0.0486
Epoch 69/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 426us/step - accuracy: 0.9799 - loss: 0.0477
Epoch 70/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 453us/step - accuracy: 0.9785 - loss: 0.0472
Epoch 71/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.9802 - loss: 0.0474
Epoch 72/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 450us/step - accuracy: 0.9789 - loss: 0.0488
Epoch 73/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 414us/step - accuracy: 0.9790 - loss: 0.0476
Epoch 74/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 564us/step - accuracy: 0.9793 - loss: 0.0471
Epoch 75/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 409us/step - accuracy: 0.9788 - loss: 0.0476
Epoch 76/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 410us/step - accuracy: 0.9787 - loss: 0.0472
Epoch 77/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.9792 - loss: 0.0465
Epoch 78/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 516us/step - accuracy: 0.9807 - loss: 0.0461
Epoch 79/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 477us/step - accuracy: 0.9791 - loss: 0.0466
Epoch 80/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 439us/step - accuracy: 0.9794 - loss: 0.0475
Epoch 81/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.9799 - loss: 0.0468
Epoch 82/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 457us/step - accuracy: 0.9795 - loss: 0.0468
Epoch 83/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 444us/step - accuracy: 0.9801 - loss: 0.0462
Epoch 84/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 416us/step - accuracy: 0.9806 - loss: 0.0456
Epoch 85/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.9803 - loss: 0.0449
Epoch 86/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 437us/step - accuracy: 0.9802 - loss: 0.0456
Epoch 87/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 556us/step - accuracy: 0.9805 - loss: 0.0456
Epoch 88/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 443us/step - accuracy: 0.9789 - loss: 0.0453
Epoch 89/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 445us/step - accuracy: 0.9801 - loss: 0.0439
Epoch 90/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 606us/step - accuracy: 0.9801 - loss: 0.0453
Epoch 91/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 630us/step - accuracy: 0.9811 - loss: 0.0447
Epoch 92/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 554us/step - accuracy: 0.9803 - loss: 0.0457
Epoch 93/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 674us/step - accuracy: 0.9799 - loss: 0.0438
Epoch 94/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 682us/step - accuracy: 0.9803 - loss: 0.0443
Epoch 95/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - accuracy: 0.9807 - loss: 0.0445
Epoch 96/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 572us/step - accuracy: 0.9805 - loss: 0.0439
Epoch 97/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 539us/step - accuracy: 0.9807 - loss: 0.0441
Epoch 98/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 560us/step - accuracy: 0.9803 - loss: 0.0443
Epoch 99/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 522us/step - accuracy: 0.9809 - loss: 0.0438
Epoch 100/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 475us/step - accuracy: 0.9809 - loss: 0.0436

In [45]:
model.evaluate(np.array(X_train),np.array(y_train))

469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 396us/step - accuracy: 0.9852 - loss: 0.0388

[0.03880469501018524, 0.9851999878883362]

In [46]:
model.evaluate(np.array(X_test),np.array(y_test))

157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 455us/step - accuracy: 0.9866 - loss: 0.0388

[0.038768965750932693, 0.9865972995758057]

In [ ]:
# evaluate는 트레인과 테스트를 봐야 함

In [63]:
model = keras.Sequential()
model.add(Input(shape=(2,)))
model.add(keras.layers.Dense(256,activation='relu')) # 입력층보다 많아야 함
model.add(keras.layers.Dense(128,activation='leaky_relu')) # 이렇게 추가해서 쓸 수 있음 _ 예측력이 좋아졌을떄 추가 하고, 떨어지면 안하는 게 좋음 / 처음엔 반절부터 시작해야 함
model.add(keras.layers.Dense(3,activation='softmax'))

In [64]:
model.compile(
    optimizer= 'rmsprop',
    loss ='categorical_crossentropy',
    metrics =['accuracy']
)

In [65]:
# 학습 시키기 
import numpy as np
model.fit(
    np.array(X_train),
    np.array(y_train),
    epochs = 100, # 처음에 5로 해본 뒤 , 50번씩 해보기
    
)

Epoch 1/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 3s 757us/step - accuracy: 0.8505 - loss: 0.3985
Epoch 2/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 588us/step - accuracy: 0.9488 - loss: 0.1431
Epoch 3/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 556us/step - accuracy: 0.9565 - loss: 0.1100
Epoch 4/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 569us/step - accuracy: 0.9569 - loss: 0.1018
Epoch 5/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9607 - loss: 0.0940
Epoch 6/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 636us/step - accuracy: 0.9621 - loss: 0.0890
Epoch 7/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 573us/step - accuracy: 0.9631 - loss: 0.0857
Epoch 8/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 559us/step - accuracy: 0.9649 - loss: 0.0836
Epoch 9/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 545us/step - accuracy: 0.9653 - loss: 0.0797
Epoch 10/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 602us/step - accuracy: 0.9684 - loss: 0.0759
Epoch 11/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 557us/step - accuracy: 0.9671 - loss: 0.0747
Epoch 12/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 547us/step - accuracy: 0.9668 - loss: 0.0754
Epoch 13/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 595us/step - accuracy: 0.9686 - loss: 0.0717
Epoch 14/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 575us/step - accuracy: 0.9697 - loss: 0.0725
Epoch 15/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 812us/step - accuracy: 0.9711 - loss: 0.0685
Epoch 16/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 574us/step - accuracy: 0.9709 - loss: 0.0688
Epoch 17/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 767us/step - accuracy: 0.9698 - loss: 0.0702
Epoch 18/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 794us/step - accuracy: 0.9727 - loss: 0.0656
Epoch 19/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 553us/step - accuracy: 0.9716 - loss: 0.0665
Epoch 20/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 567us/step - accuracy: 0.9715 - loss: 0.0656
Epoch 21/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 578us/step - accuracy: 0.9741 - loss: 0.0624
Epoch 22/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 560us/step - accuracy: 0.9733 - loss: 0.0631
Epoch 23/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 555us/step - accuracy: 0.9744 - loss: 0.0621
Epoch 24/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 563us/step - accuracy: 0.9742 - loss: 0.0614
Epoch 25/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 555us/step - accuracy: 0.9740 - loss: 0.0628
Epoch 26/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 553us/step - accuracy: 0.9737 - loss: 0.0611
Epoch 27/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 702us/step - accuracy: 0.9740 - loss: 0.0592
Epoch 28/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 550us/step - accuracy: 0.9743 - loss: 0.0601
Epoch 29/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 554us/step - accuracy: 0.9742 - loss: 0.0570
Epoch 30/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 567us/step - accuracy: 0.9750 - loss: 0.0580
Epoch 31/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 539us/step - accuracy: 0.9747 - loss: 0.0583
Epoch 32/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 534us/step - accuracy: 0.9760 - loss: 0.0556
Epoch 33/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 573us/step - accuracy: 0.9753 - loss: 0.0594
Epoch 34/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 555us/step - accuracy: 0.9785 - loss: 0.0554
Epoch 35/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 557us/step - accuracy: 0.9784 - loss: 0.0547
Epoch 36/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 561us/step - accuracy: 0.9771 - loss: 0.0558
Epoch 37/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 553us/step - accuracy: 0.9767 - loss: 0.0559
Epoch 38/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 601us/step - accuracy: 0.9781 - loss: 0.0539
Epoch 39/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 536us/step - accuracy: 0.9757 - loss: 0.0552
Epoch 40/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 781us/step - accuracy: 0.9753 - loss: 0.0558
Epoch 41/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 556us/step - accuracy: 0.9765 - loss: 0.0547
Epoch 42/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 546us/step - accuracy: 0.9777 - loss: 0.0534
Epoch 43/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 531us/step - accuracy: 0.9759 - loss: 0.0542
Epoch 44/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 578us/step - accuracy: 0.9768 - loss: 0.0538
Epoch 45/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 550us/step - accuracy: 0.9768 - loss: 0.0559
Epoch 46/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 566us/step - accuracy: 0.9760 - loss: 0.0542
Epoch 47/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 549us/step - accuracy: 0.9788 - loss: 0.0520
Epoch 48/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 609us/step - accuracy: 0.9773 - loss: 0.0548
Epoch 49/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 667us/step - accuracy: 0.9790 - loss: 0.0512
Epoch 50/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 676us/step - accuracy: 0.9768 - loss: 0.0527
Epoch 51/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 636us/step - accuracy: 0.9794 - loss: 0.0484
Epoch 52/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.9788 - loss: 0.0513
Epoch 53/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - accuracy: 0.9785 - loss: 0.0499
Epoch 54/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 555us/step - accuracy: 0.9788 - loss: 0.0521
Epoch 55/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 542us/step - accuracy: 0.9799 - loss: 0.0478
Epoch 56/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 546us/step - accuracy: 0.9793 - loss: 0.0494
Epoch 57/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 546us/step - accuracy: 0.9804 - loss: 0.0478
Epoch 58/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 564us/step - accuracy: 0.9799 - loss: 0.0476
Epoch 59/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 546us/step - accuracy: 0.9781 - loss: 0.0493
Epoch 60/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 543us/step - accuracy: 0.9789 - loss: 0.0508
Epoch 61/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 549us/step - accuracy: 0.9792 - loss: 0.0487
Epoch 62/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 543us/step - accuracy: 0.9792 - loss: 0.0485
Epoch 63/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 564us/step - accuracy: 0.9790 - loss: 0.0509
Epoch 64/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 681us/step - accuracy: 0.9795 - loss: 0.0469
Epoch 65/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 545us/step - accuracy: 0.9804 - loss: 0.0475
Epoch 66/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 548us/step - accuracy: 0.9796 - loss: 0.0482
Epoch 67/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 567us/step - accuracy: 0.9789 - loss: 0.0499
Epoch 68/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 558us/step - accuracy: 0.9812 - loss: 0.0474
Epoch 69/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 545us/step - accuracy: 0.9781 - loss: 0.0491
Epoch 70/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 533us/step - accuracy: 0.9796 - loss: 0.0458
Epoch 71/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 551us/step - accuracy: 0.9807 - loss: 0.0485
Epoch 72/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 542us/step - accuracy: 0.9805 - loss: 0.0464
Epoch 73/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 545us/step - accuracy: 0.9799 - loss: 0.0464
Epoch 74/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 559us/step - accuracy: 0.9790 - loss: 0.0469
Epoch 75/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 556us/step - accuracy: 0.9793 - loss: 0.0487
Epoch 76/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 804us/step - accuracy: 0.9806 - loss: 0.0462
Epoch 77/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 552us/step - accuracy: 0.9810 - loss: 0.0464
Epoch 78/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 568us/step - accuracy: 0.9802 - loss: 0.0453
Epoch 79/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 551us/step - accuracy: 0.9814 - loss: 0.0458
Epoch 80/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 548us/step - accuracy: 0.9809 - loss: 0.0452
Epoch 81/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 576us/step - accuracy: 0.9809 - loss: 0.0463
Epoch 82/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 550us/step - accuracy: 0.9811 - loss: 0.0469
Epoch 83/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 573us/step - accuracy: 0.9819 - loss: 0.0441
Epoch 84/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 558us/step - accuracy: 0.9815 - loss: 0.0471
Epoch 85/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 550us/step - accuracy: 0.9805 - loss: 0.0457
Epoch 86/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 577us/step - accuracy: 0.9809 - loss: 0.0434
Epoch 87/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 691us/step - accuracy: 0.9815 - loss: 0.0448
Epoch 88/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 582us/step - accuracy: 0.9808 - loss: 0.0436
Epoch 89/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 976us/step - accuracy: 0.9821 - loss: 0.0427
Epoch 90/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 561us/step - accuracy: 0.9827 - loss: 0.0422
Epoch 91/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 568us/step - accuracy: 0.9812 - loss: 0.0446
Epoch 92/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 578us/step - accuracy: 0.9811 - loss: 0.0428
Epoch 93/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 551us/step - accuracy: 0.9820 - loss: 0.0419
Epoch 94/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 576us/step - accuracy: 0.9800 - loss: 0.0463
Epoch 95/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 559us/step - accuracy: 0.9816 - loss: 0.0428
Epoch 96/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 605us/step - accuracy: 0.9808 - loss: 0.0456
Epoch 97/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 975us/step - accuracy: 0.9811 - loss: 0.0432
Epoch 98/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 562us/step - accuracy: 0.9819 - loss: 0.0423
Epoch 99/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 560us/step - accuracy: 0.9808 - loss: 0.0438
Epoch 100/100
469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 580us/step - accuracy: 0.9815 - loss: 0.0442

In [66]:
model.evaluate(np.array(X_train),np.array(y_train))

469/469 ━━━━━━━━━━━━━━━━━━━━ 0s 402us/step - accuracy: 0.9889 - loss: 0.0258

[0.02584780566394329, 0.9889333248138428]

In [67]:
model.evaluate(np.array(X_test),np.array(y_test))

157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 475us/step - accuracy: 0.9882 - loss: 0.0271

[0.027104437351226807, 0.9881976246833801]